[package]
name = "woe"
version = "0.1.0"
authors = ["Andrew Lilley Brinker <andrewabrinker@gmail.com>"]
description = """
    A Result type that differentiates between local errors (which can be handled)
    and fatal errors (which cannot)
"""
license = "MIT OR Apache-2.0"
edition = "2018"
categories = ["Rust patterns"]
keywords = ["result", "error-handling"]
