[package]
name = "woe"
version = "0.1.6"
authors = ["Andrew Lilley Brinker <andrewabrinker@gmail.com>"]
description = """
    A Result type that differentiates between local errors (which can be handled)
    and fatal errors (which cannot)
"""
license = "MIT OR Apache-2.0"
edition = "2018"
categories = ["rust-patterns"]
keywords = ["result", "error-handling"]
repository = "https://github.com/alilleybrinker/woe/"
readme = "README.md"

[dependencies]
either = { version = "1.5", optional = true }

[features]
default = ["either-methods"]
either-methods = ["either"]
